### ISSUE TITLE
Every component is refreshing 

### ISSUE THREAD

**Issue by Ayush-may** [deminearchiver/tab#1]
You are using react but why is every component refreshing 
it is not optimize , this issue need to be fixed

https://github.com/deminearchiver/tab/assets/112775332/b4bbe32a-53b3-470c-b63f-0d5647e1f9e7

**Comment by deminearchiver** [comment]
Good evening!
Are you sure you posted the issue in the correct repo? Because the extension I'm seeing is tabliss, to which I am unrelated. My extension uses SolidJS which doesn't re-render everything.
